// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: orm/paginator/paginator.proto

package paginator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchParam
type SearchParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // 字段
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 值
	Exp   string `protobuf:"bytes,3,opt,name=exp,proto3" json:"exp,omitempty"`     // 操作 "=", "!=", ">", ">=", "<", "<=", "IN", "NOT IN", "LIKE", "NOT LIKE"
	Logic string `protobuf:"bytes,4,opt,name=logic,proto3" json:"logic,omitempty"` // 逻辑关系
}

func (x *SearchParam) Reset() {
	*x = SearchParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orm_paginator_paginator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchParam) ProtoMessage() {}

func (x *SearchParam) ProtoReflect() protoreflect.Message {
	mi := &file_orm_paginator_paginator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchParam.ProtoReflect.Descriptor instead.
func (*SearchParam) Descriptor() ([]byte, []int) {
	return file_orm_paginator_paginator_proto_rawDescGZIP(), []int{0}
}

func (x *SearchParam) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchParam) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *SearchParam) GetLogic() string {
	if x != nil {
		return x.Logic
	}
	return ""
}

// OrderParam
type OrderParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // 字段
	Exp   string `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`     // 表达式 ASC,DESC
}

func (x *OrderParam) Reset() {
	*x = OrderParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orm_paginator_paginator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderParam) ProtoMessage() {}

func (x *OrderParam) ProtoReflect() protoreflect.Message {
	mi := &file_orm_paginator_paginator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderParam.ProtoReflect.Descriptor instead.
func (*OrderParam) Descriptor() ([]byte, []int) {
	return file_orm_paginator_paginator_proto_rawDescGZIP(), []int{1}
}

func (x *OrderParam) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OrderParam) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

// PaginatorReq
type PaginatorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         //页码
	PageSize int32          `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` //页数
	Search   []*SearchParam `protobuf:"bytes,3,rep,name=search,proto3" json:"search,omitempty"`      //详细搜索
	Order    []*OrderParam  `protobuf:"bytes,4,rep,name=order,proto3" json:"order,omitempty"`        //排序
}

func (x *PaginatorReq) Reset() {
	*x = PaginatorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orm_paginator_paginator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatorReq) ProtoMessage() {}

func (x *PaginatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_orm_paginator_paginator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatorReq.ProtoReflect.Descriptor instead.
func (*PaginatorReq) Descriptor() ([]byte, []int) {
	return file_orm_paginator_paginator_proto_rawDescGZIP(), []int{2}
}

func (x *PaginatorReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatorReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginatorReq) GetSearch() []*SearchParam {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *PaginatorReq) GetOrder() []*OrderParam {
	if x != nil {
		return x.Order
	}
	return nil
}

// PaginatorReply
type PaginatorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`           //第几页
	PageSize  int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`   //页大小
	Total     int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`         //总数
	PrevPage  int32 `protobuf:"varint,4,opt,name=prevPage,proto3" json:"prevPage,omitempty"`   //上一页
	NextPage  int32 `protobuf:"varint,5,opt,name=nextPage,proto3" json:"nextPage,omitempty"`   //下一页
	TotalPage int32 `protobuf:"varint,6,opt,name=totalPage,proto3" json:"totalPage,omitempty"` //总页数
}

func (x *PaginatorReply) Reset() {
	*x = PaginatorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orm_paginator_paginator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatorReply) ProtoMessage() {}

func (x *PaginatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_orm_paginator_paginator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatorReply.ProtoReflect.Descriptor instead.
func (*PaginatorReply) Descriptor() ([]byte, []int) {
	return file_orm_paginator_paginator_proto_rawDescGZIP(), []int{3}
}

func (x *PaginatorReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatorReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginatorReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginatorReply) GetPrevPage() int32 {
	if x != nil {
		return x.PrevPage
	}
	return 0
}

func (x *PaginatorReply) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

func (x *PaginatorReply) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

var File_orm_paginator_paginator_proto protoreflect.FileDescriptor

var file_orm_paginator_paginator_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x61, 0x0a, 0x0b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x22, 0x34, 0x0a,
	0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x78, 0x70, 0x22, 0x9b, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x2b, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x22, 0xac, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72,
	0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x7a, 0x66, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x66, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x72, 0x6d,
	0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x3b, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orm_paginator_paginator_proto_rawDescOnce sync.Once
	file_orm_paginator_paginator_proto_rawDescData = file_orm_paginator_paginator_proto_rawDesc
)

func file_orm_paginator_paginator_proto_rawDescGZIP() []byte {
	file_orm_paginator_paginator_proto_rawDescOnce.Do(func() {
		file_orm_paginator_paginator_proto_rawDescData = protoimpl.X.CompressGZIP(file_orm_paginator_paginator_proto_rawDescData)
	})
	return file_orm_paginator_paginator_proto_rawDescData
}

var file_orm_paginator_paginator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orm_paginator_paginator_proto_goTypes = []interface{}{
	(*SearchParam)(nil),    // 0: paginator.SearchParam
	(*OrderParam)(nil),     // 1: paginator.OrderParam
	(*PaginatorReq)(nil),   // 2: paginator.PaginatorReq
	(*PaginatorReply)(nil), // 3: paginator.PaginatorReply
}
var file_orm_paginator_paginator_proto_depIdxs = []int32{
	0, // 0: paginator.PaginatorReq.search:type_name -> paginator.SearchParam
	1, // 1: paginator.PaginatorReq.order:type_name -> paginator.OrderParam
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orm_paginator_paginator_proto_init() }
func file_orm_paginator_paginator_proto_init() {
	if File_orm_paginator_paginator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orm_paginator_paginator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orm_paginator_paginator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orm_paginator_paginator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginatorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orm_paginator_paginator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginatorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orm_paginator_paginator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_paginator_paginator_proto_goTypes,
		DependencyIndexes: file_orm_paginator_paginator_proto_depIdxs,
		MessageInfos:      file_orm_paginator_paginator_proto_msgTypes,
	}.Build()
	File_orm_paginator_paginator_proto = out.File
	file_orm_paginator_paginator_proto_rawDesc = nil
	file_orm_paginator_paginator_proto_goTypes = nil
	file_orm_paginator_paginator_proto_depIdxs = nil
}
